### ISSUE TITLE
Pass array of vectors as uniform array.

### ISSUE THREAD

**Issue by nassosyian** [google/swissgl#4]
First off, i love what you are doing with this project. 

I might be missing something, but is there a way to pass an array of vectors 
as a uniform array ie. `uniform vec4 colors[count];` ?
I don't want to inline them because they might be animated and 
the cost recompiling the fragment shader on every frame seems high.

**Comment by znah** [comment]
Uniform arrays are not supported yet, I'll think about good ways of adding them. Currently data textures may be an option of passing arrays of data to GPU (see [Spectrogram](https://github.com/google/swissgl/blob/main/demo/Spectrogram.js) example)

**Comment by znah** [comment]
https://github.com/google/swissgl/commit/52e5fd046378014bb434c217f7bb4e639c76ba3a
